/**
 * TradingView `coin/scan` column ids + stable storage keys.
 * Column names must match TV’s API (pipe `|` for time-sliced fields, `Perf.*`, `Volatility.*`, etc.).
 */

export type CryptoScanFieldKind = "json" | "num" | "pct" | "usd" | "strings" | "raw";

export type CryptoScanField = {
  /** Mongo-safe key under `tradingview_scan` */
  key: string;
  /** TradingView scanner column id */
  column: string;
  kind: CryptoScanFieldKind;
};

/**
 * Order is fixed: `d[i]` in each scan row matches `CRYPTO_SCAN_FIELDS[i]`.
 */
export const CRYPTO_SCAN_FIELDS: readonly CryptoScanField[] = [
  { key: "ticker_view", column: "ticker-view", kind: "json" },
  { key: "crypto_total_rank", column: "crypto_total_rank", kind: "num" },
  { key: "crypto_blockchain_ecosystems", column: "crypto_blockchain_ecosystems", kind: "strings" },
  { key: "crypto_common_categories", column: "crypto_common_categories", kind: "strings" },
  { key: "circulating_supply", column: "circulating_supply", kind: "num" },
  { key: "crypto_consensus_algorithms", column: "crypto_consensus_algorithms", kind: "strings" },
  { key: "max_supply", column: "max_supply", kind: "num" },
  { key: "total_supply", column: "total_supply", kind: "num" },
  { key: "tvl", column: "tvl", kind: "usd" },
  { key: "type", column: "type", kind: "raw" },
  { key: "typespecs", column: "typespecs", kind: "strings" },
  { key: "fundamental_currency_code", column: "fundamental_currency_code", kind: "raw" },
  { key: "change_from_open", column: "change_from_open", kind: "pct" },
  { key: "change_from_open_1W", column: "change_from_open|1W", kind: "pct" },
  { key: "change_from_open_1M", column: "change_from_open|1M", kind: "pct" },
  { key: "change_from_open_abs", column: "change_from_open_abs", kind: "usd" },
  { key: "pricescale", column: "pricescale", kind: "num" },
  { key: "minmov", column: "minmov", kind: "num" },
  { key: "fractional", column: "fractional", kind: "raw" },
  { key: "minmove2", column: "minmove2", kind: "num" },
  { key: "currency", column: "currency", kind: "raw" },
  { key: "change_from_open_abs_1W", column: "change_from_open_abs|1W", kind: "usd" },
  { key: "change_from_open_abs_1M", column: "change_from_open_abs|1M", kind: "usd" },
  { key: "gap", column: "gap", kind: "pct" },
  { key: "gap_1W", column: "gap|1W", kind: "pct" },
  { key: "gap_1M", column: "gap|1M", kind: "pct" },
  { key: "high", column: "high", kind: "usd" },
  { key: "high_1W", column: "high|1W", kind: "usd" },
  { key: "high_1M", column: "high|1M", kind: "usd" },
  { key: "high_1M_2", column: "high|1M_2", kind: "usd" },
  { key: "high_3M", column: "high|3M", kind: "usd" },
  { key: "high_6M", column: "high|6M", kind: "usd" },
  { key: "price_52_week_high", column: "price_52_week_high", kind: "usd" },
  { key: "high_all", column: "High.All", kind: "usd" },
  { key: "low", column: "low", kind: "usd" },
  { key: "low_1W", column: "low|1W", kind: "usd" },
  { key: "low_1M", column: "low|1M", kind: "usd" },
  { key: "low_1M_2", column: "low|1M_2", kind: "usd" },
  { key: "low_3M", column: "low|3M", kind: "usd" },
  { key: "low_6M", column: "low|6M", kind: "usd" },
  { key: "price_52_week_low", column: "price_52_week_low", kind: "usd" },
  { key: "low_all", column: "Low.All", kind: "usd" },
  { key: "open", column: "open", kind: "usd" },
  { key: "open_1W", column: "open|1W", kind: "usd" },
  { key: "open_1M", column: "open|1M", kind: "usd" },
  { key: "perf_W", column: "Perf.W", kind: "pct" },
  { key: "perf_1M", column: "Perf.1M", kind: "pct" },
  { key: "perf_3M", column: "Perf.3M", kind: "pct" },
  { key: "perf_6M", column: "Perf.6M", kind: "pct" },
  { key: "perf_YTD", column: "Perf.YTD", kind: "pct" },
  { key: "perf_Y", column: "Perf.Y", kind: "pct" },
  { key: "perf_5Y", column: "Perf.5Y", kind: "pct" },
  { key: "perf_10Y", column: "Perf.10Y", kind: "pct" },
  { key: "perf_All", column: "Perf.All", kind: "pct" },
  { key: "close", column: "close", kind: "usd" },
  { key: "change_abs", column: "change_abs", kind: "usd" },
  { key: "change_abs_1W", column: "change_abs|1W", kind: "usd" },
  { key: "change_abs_1M", column: "change_abs|1M", kind: "usd" },
  { key: "change", column: "change", kind: "pct" },
  { key: "change_1W", column: "change|1W", kind: "pct" },
  { key: "change_1M", column: "change|1M", kind: "pct" },
  { key: "change_24h_close_change_5", column: "change|24h_close_change_5", kind: "pct" },
  { key: "volatilityD", column: "Volatility.D", kind: "pct" },
  { key: "volatilityW", column: "Volatility.W", kind: "pct" },
  { key: "volatilityM", column: "Volatility.M", kind: "pct" },
  { key: "vcm_24h_vol_change_cmc", column: "24h_vol_change_cmc", kind: "pct" },
  { key: "vc_24h_vol_cmc", column: "24h_vol_cmc", kind: "usd" },
  { key: "market_cap_diluted_calc", column: "market_cap_diluted_calc", kind: "usd" },
  { key: "market_cap_calc", column: "market_cap_calc", kind: "usd" },
  { key: "market_cap_to_tvl", column: "market_cap_to_tvl", kind: "num" },
  { key: "nvt", column: "nvt", kind: "num" },
  { key: "velocity", column: "velocity", kind: "num" },
  { key: "vtmkc_24h_vol_to_market_cap", column: "24h_vol_to_market_cap", kind: "num" },
  { key: "total_addresses_with_balance", column: "total_addresses_with_balance", kind: "num" },
  { key: "addresses_active", column: "addresses_active", kind: "num" },
  { key: "addresses_new", column: "addresses_new", kind: "num" },
  { key: "average_transaction_usd", column: "average_transaction_usd", kind: "usd" },
  { key: "large_tx_count", column: "large_tx_count", kind: "num" },
  { key: "large_tx_volume_usd", column: "large_tx_volume_usd", kind: "usd" },
  { key: "txs_count", column: "txs_count", kind: "num" },
  { key: "txs_volume", column: "txs_volume", kind: "num" },
  { key: "txs_volume_usd", column: "txs_volume_usd", kind: "usd" },
  { key: "contributorsactive", column: "contributorsactive", kind: "num" },
  { key: "postsactive", column: "postsactive", kind: "num" },
  { key: "altrank", column: "altrank", kind: "num" },
  { key: "contributorscreated", column: "contributorscreated", kind: "num" },
  { key: "postscreated", column: "postscreated", kind: "num" },
  { key: "interactions", column: "interactions", kind: "num" },
  { key: "galaxyscore", column: "galaxyscore", kind: "num" },
  { key: "sentiment", column: "sentiment", kind: "pct" },
  { key: "socialdominance", column: "socialdominance", kind: "pct" },
  { key: "social_volume_24h", column: "social_volume_24h", kind: "num" },
  { key: "telegram_positive", column: "telegram_positive", kind: "num" },
  { key: "telegram_negative", column: "telegram_negative", kind: "num" },
  { key: "tweets", column: "tweets", kind: "num" },
  { key: "aroon_up", column: "Aroon.Up", kind: "pct" },
  { key: "aroon_down", column: "Aroon.Down", kind: "pct" },
  { key: "aroon_W_up", column: "Aroon.Up|1W", kind: "pct" },
  { key: "aroon_W_down", column: "Aroon.Down|1W", kind: "pct" },
  { key: "aroon_M_up", column: "Aroon.Up|1M", kind: "pct" },
  { key: "aroon_M_down", column: "Aroon.Down|1M", kind: "pct" },
  { key: "adr", column: "ADR", kind: "num" },
  { key: "adrp", column: "ADRP", kind: "pct" },
  { key: "adx_9_D", column: "ADX|9", kind: "num" },
  { key: "adx_20_D", column: "ADX|20", kind: "num" },
  { key: "adx_50_D", column: "ADX|50", kind: "num" },
  { key: "adx_100_D", column: "ADX|100", kind: "num" },
  { key: "adx_plus_di_9", column: "ADX+DI|9", kind: "num" },
  { key: "adx_minus_di_9", column: "ADX-DI|9", kind: "num" },
  { key: "adx_plus_di_20", column: "ADX+DI|20", kind: "num" },
  { key: "adx_minus_di_20", column: "ADX-DI|20", kind: "num" },
  { key: "adx_plus_di_50", column: "ADX+DI|50", kind: "num" },
  { key: "adx_minus_di_50", column: "ADX-DI|50", kind: "num" },
  { key: "adx_plus_di_100", column: "ADX+DI|100", kind: "num" },
  { key: "adx_minus_di_100", column: "ADX-DI|100", kind: "num" },
  { key: "atr_D", column: "ATR|14", kind: "num" },
  { key: "atr_W", column: "ATR|1W", kind: "num" },
  { key: "atr_M", column: "ATR|1M", kind: "num" },
  { key: "atrp_D", column: "ATRP", kind: "pct" },
  { key: "atrp_W", column: "ATRP|1W", kind: "pct" },
  { key: "atrp_M", column: "ATRP|1M", kind: "pct" },
  { key: "ao_D", column: "AO|1", kind: "num" },
  { key: "ao_W", column: "AO|1W", kind: "num" },
  { key: "ao_M", column: "AO|1M", kind: "num" },
  { key: "bb_upper_D", column: "BB.upper|1", kind: "num" },
  { key: "bb_basis_D", column: "BB.basis|1", kind: "num" },
  { key: "bb_lower_D", column: "BB.lower|1", kind: "num" },
  { key: "bb_upper_W", column: "BB.upper|1W", kind: "num" },
  { key: "bb_basis_W", column: "BB.basis|1W", kind: "num" },
  { key: "bb_lower_W", column: "BB.lower|1W", kind: "num" },
  { key: "bb_upper_M", column: "BB.upper|1M", kind: "num" },
  { key: "bb_basis_M", column: "BB.basis|1M", kind: "num" },
  { key: "bb_lower_M", column: "BB.lower|1M", kind: "num" },
  { key: "bb_upper_50_D", column: "BB.upper|50", kind: "num" },
  { key: "bb_basis_50_D", column: "BB.basis|50", kind: "num" },
  { key: "bb_lower_50_D", column: "BB.lower|50", kind: "num" },
  { key: "bb_power_D", column: "BBPower|1", kind: "num" },
  { key: "bb_power_W", column: "BBPower|1W", kind: "num" },
  { key: "bb_power_M", column: "BBPower|1M", kind: "num" },
  { key: "bb_power_50", column: "BBPower|50", kind: "num" },
  { key: "cci_20_D", column: "CCI20|1D", kind: "num" },
  { key: "cci_20_W", column: "CCI20|1W", kind: "num" },
  { key: "cci_20_M", column: "CCI20|1M", kind: "num" },
  { key: "mom_D", column: "Mom", kind: "num" },
  { key: "mom_W", column: "Mom|1W", kind: "num" },
  { key: "mom_M", column: "Mom|1M", kind: "num" },
  { key: "mom_14_D", column: "Mom|14", kind: "num" },
  { key: "macd_macd_D", column: "MACD.macd", kind: "num" },
  { key: "macd_signal_D", column: "MACD.signal", kind: "num" },
  { key: "macd_macd_W", column: "MACD.macd|1W", kind: "num" },
  { key: "macd_signal_W", column: "MACD.signal|1W", kind: "num" },
  { key: "macd_macd_M", column: "MACD.macd|1M", kind: "num" },
  { key: "macd_signal_M", column: "MACD.signal|1M", kind: "num" },
  { key: "ma_rating_D", column: "Recommend.All|1D", kind: "num" },
  { key: "ma_rating_D_tr", column: "Recommend.Other|1D", kind: "num" },
  { key: "ma_rating_W", column: "Recommend.All|1W", kind: "num" },
  { key: "ma_rating_W_tr", column: "Recommend.Other|1W", kind: "num" },
  { key: "ma_rating_M", column: "Recommend.All|1M", kind: "num" },
  { key: "ma_rating_M_tr", column: "Recommend.Other|1M", kind: "num" },
  { key: "rsi_D", column: "RSI", kind: "num" },
  { key: "rsi_W", column: "RSI|W", kind: "num" },
  { key: "rsi_M", column: "RSI|M", kind: "num" },
  { key: "rsi_7_D", column: "RSI|7", kind: "num" },
  { key: "rsi_20_D", column: "RSI|20", kind: "num" },
  { key: "rsi_21_D", column: "RSI|21", kind: "num" },
  { key: "rsi_30_D", column: "RSI|30", kind: "num" },
  /** Coin scanner exposes weekly/monthly RSI only for the 30-period variant. */
  { key: "rsi_30_W", column: "RSI|30|W", kind: "num" },
  { key: "rsi_30_M", column: "RSI|30|M", kind: "num" },
  { key: "sma_7_D", column: "SMA7", kind: "num" },
  { key: "sma_7_W", column: "SMA7|1W", kind: "num" },
  { key: "sma_7_M", column: "SMA7|1M", kind: "num" },
  { key: "sma_14_D", column: "SMA14", kind: "num" },
  { key: "sma_14_W", column: "SMA14|1W", kind: "num" },
  { key: "sma_14_M", column: "SMA14|1M", kind: "num" },
  { key: "sma_21_D", column: "SMA21", kind: "num" },
  { key: "sma_21_W", column: "SMA21|1W", kind: "num" },
  { key: "sma_21_M", column: "SMA21|1M", kind: "num" },
  { key: "sma_50_D", column: "SMA50", kind: "num" },
  { key: "sma_50_W", column: "SMA50|1W", kind: "num" },
  { key: "sma_50_M", column: "SMA50|1M", kind: "num" },
  { key: "sma_100_D", column: "SMA100", kind: "num" },
  { key: "sma_100_W", column: "SMA100|1W", kind: "num" },
  { key: "sma_100_M", column: "SMA100|1M", kind: "num" },
  { key: "sma_150_D", column: "SMA150", kind: "num" },
  { key: "sma_150_W", column: "SMA150|1W", kind: "num" },
  { key: "sma_150_M", column: "SMA150|1M", kind: "num" },
  { key: "sma_300_D", column: "SMA300", kind: "num" },
  { key: "sma_300_W", column: "SMA300|1W", kind: "num" },
  { key: "sma_300_M", column: "SMA300|1M", kind: "num" },
  { key: "sma_200_D", column: "SMA200", kind: "num" },
  { key: "sma_200_W", column: "SMA200|1W", kind: "num" },
  { key: "sma_200_M", column: "SMA200|1M", kind: "num" },
];

export const CRYPTO_SCAN_COLUMN_IDS: readonly string[] = CRYPTO_SCAN_FIELDS.map((f) => f.column);
